# Generated by Django 2.0.7 on 2018-07-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssitemfb',
            name='rss_text',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='rssitemtw',
            name='rss_text',
            field=models.TextField(null=True, verbose_name='text'),
        ),
    ]
