# Generated by Django 2.0.7 on 2018-08-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsser', '0002_auto_20180728_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_text_fb', models.TextField(null=True, verbose_name='text_fb')),
                ('rss_text_tw', models.TextField(null=True, verbose_name='text_tw')),
                ('rss_link', models.CharField(max_length=200, verbose_name='link')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='RssItemFb',
        ),
        migrations.DeleteModel(
            name='RssItemTw',
        ),
    ]
