# Generated by Django 2.0.7 on 2018-08-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsser', '0003_auto_20180801_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='rss',
            name='is_fb',
            field=models.BooleanField(default=False, verbose_name='Facebook?'),
        ),
        migrations.AddField(
            model_name='rss',
            name='is_parser',
            field=models.BooleanField(default=True, verbose_name='парсить?'),
        ),
        migrations.AddField(
            model_name='rss',
            name='is_teleg',
            field=models.BooleanField(default=False, verbose_name='Telegram?'),
        ),
        migrations.AddField(
            model_name='rss',
            name='is_tw',
            field=models.BooleanField(default=False, verbose_name='Twitter?'),
        ),
        migrations.AddField(
            model_name='rss',
            name='is_vk',
            field=models.BooleanField(default=False, verbose_name='Вконтакте?'),
        ),
    ]
