# Generated by Django 2.0.7 on 2018-08-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsser', '0004_auto_20180801_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='rss',
            name='is_parser_tw',
            field=models.BooleanField(default=False, verbose_name='парсить заголовок для tw?'),
        ),
        migrations.AlterField(
            model_name='rss',
            name='is_parser',
            field=models.BooleanField(default=True, verbose_name='парсить fb?'),
        ),
        migrations.AlterField(
            model_name='rss',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='rss',
            name='rss_text_fb',
            field=models.TextField(blank=True, null=True, verbose_name='text_fb'),
        ),
        migrations.AlterField(
            model_name='rss',
            name='rss_text_tw',
            field=models.CharField(blank=True, max_length=257, null=True, verbose_name='text_tw'),
        ),
    ]
