# Generated by Django 2.0.7 on 2018-08-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsser', '0007_auto_20180804_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rss',
            name='is_parser',
        ),
        migrations.RemoveField(
            model_name='rss',
            name='is_parser_tw',
        ),
    ]
