# Generated by Django 2.0.7 on 2018-08-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsser', '0008_auto_20180806_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rss',
            name='is_tw',
        ),
        migrations.AddField(
            model_name='rss',
            name='is_tiw',
            field=models.BooleanField(default=False, verbose_name='Twitter?'),
        ),
    ]
