# Generated by Django 2.0.7 on 2018-08-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsser', '0010_auto_20180808_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teleg', models.BooleanField(default=False, verbose_name='Telegram?')),
                ('is_vk', models.BooleanField(default=False, verbose_name='Вконтакте?')),
                ('is_fb', models.BooleanField(default=False, verbose_name='Facebook?')),
                ('is_tw', models.BooleanField(default=False, verbose_name='Twitter?')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('rss_link', models.CharField(max_length=200, verbose_name='link')),
                ('rss_image_tw', models.CharField(blank=True, max_length=200, null=True, verbose_name='image link')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsser.Switches')),
            ],
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_text_fb', models.TextField(blank=True, null=True, verbose_name='text_fb')),
                ('rss_text_tw', models.CharField(blank=True, max_length=257, null=True, verbose_name='text_tw')),
            ],
        ),
        migrations.DeleteModel(
            name='Rss',
        ),
        migrations.AddField(
            model_name='switchmatching',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsser.Texts'),
        ),
        migrations.AddField(
            model_name='switches',
            name='switch',
            field=models.ManyToManyField(to='rsser.Texts'),
        ),
    ]
