# Generated by Django 2.1.7 on 2019-03-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsser', '0012_auto_20180808_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rss',
            name='is_fb',
            field=models.BooleanField(default=True, verbose_name='Facebook?'),
        ),
        migrations.AlterField(
            model_name='rss',
            name='is_teleg',
            field=models.BooleanField(default=True, verbose_name='Telegram?'),
        ),
        migrations.AlterField(
            model_name='rss',
            name='is_tw',
            field=models.BooleanField(default=True, verbose_name='Twitter?'),
        ),
        migrations.AlterField(
            model_name='rss',
            name='is_vk',
            field=models.BooleanField(default=True, verbose_name='Вконтакте?'),
        ),
    ]
