# Generated by Django 2.1.7 on 2019-03-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsser', '0014_auto_20190327_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='rss',
            name='is_parse_image_tw',
            field=models.BooleanField(default=False, verbose_name='есть ссылка на картинку? (не парсить картинку?)'),
        ),
        migrations.AddField(
            model_name='rss',
            name='is_parse_text_tw',
            field=models.BooleanField(default=False, verbose_name='есть текст для tw? (не парсить текст?)'),
        ),
        migrations.AlterField(
            model_name='rss',
            name='is_fb',
            field=models.BooleanField(default=False, verbose_name='не слать в Facebook?'),
        ),
        migrations.AlterField(
            model_name='rss',
            name='is_teleg',
            field=models.BooleanField(default=False, verbose_name='не слать в Telegram?'),
        ),
        migrations.AlterField(
            model_name='rss',
            name='is_tw',
            field=models.BooleanField(default=False, verbose_name='не слать в Twitter?'),
        ),
        migrations.AlterField(
            model_name='rss',
            name='is_vk',
            field=models.BooleanField(default=False, verbose_name='не слать в Вконтакте?'),
        ),
    ]
