# Generated by Django 2.2.4 on 2019-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsser', '0015_auto_20190328_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoparsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_link', models.CharField(max_length=200, verbose_name='link')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
    ]
